version: '3'

services:
  ims-go-backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest
    ports:
      - "${PORT}:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
      - PRIVATE_TOKEN=${PRIVATE_TOKEN}
    env_file:
      - .env
